# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            RJ
tagline:          'WIP website'
description:      'WIP'
url:              https://ricardo-jay.github.io
baseurl:          /

author:
  name:           'RJ'
  url:            https://twitter.com/rt1799

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/ricardo-jay/ricardo-jay.github.io.git
